<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class StepsTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('steps')->insert([
            ['recipe_id' => 1, 'deskripsi_langkah' => 'Tumis bawang putih dan cabai merah hingga harum; tambahkan ayam suwir dan wortel, aduk rata; masukkan telur dan orak-arik hingga matang; tambahkan nasi putih, kecap manis, garam, dan merica; aduk hingga semua bahan tercampur rata dan sajikan.'],
            ['recipe_id' => 2, 'deskripsi_langkah' => 'Campurkan madu, kecap manis, air perasan jeruk nipis, bawang putih yang telah dihaluskan, garam, dan merica dalam sebuah wadah; lumuri ayam dengan campuran bumbu tersebut; diamkan selama 30 menit; panaskan minyak zaitun di atas panggangan; bakar ayam hingga matang dan berwarna kecokelatan; sajikan.'],
            ['recipe_id' => 3, 'deskripsi_langkah' => 'Rebus ayam dalam air hingga mendidih dan ayam empuk; angkat ayam dan suwir dagingnya; saring kaldu ayam dan sisihkan; tumis bawang merah, bawang putih, kemiri, lengkuas, daun salam, serai, daun jeruk, kunyit, dan ketumbar dengan minyak goreng hingga harum; masukkan tumisan bumbu ke dalam kaldu ayam; tambahkan garam, merica, dan kecap manis; biarkan mendidih selama 10 menit; sesuaikan rasa; sajikan soto ayam dalam mangkuk dengan irisan ayam suwir, telur rebus, taoge, kol, daun bawang, dan seledri; beri sambal, kerupuk, dan perasan jeruk nipis sesuai selera.'],
            ['recipe_id' => 4, 'deskripsi_langkah' => 'Kupas dan potong mangga; masukkan mangga ke dalam blender bersama yogurt, madu, dan sedikit air; tambahkan es batu secukupnya, blender hingga halus; tuang ke dalam gelas dan sajikan segera.'],
            ['recipe_id' => 5, 'deskripsi_langkah' => 'Rebus ayam dalam air hingga mendidih, buang buihnya; tambahkan jahe yang sudah dimemarkan, bawang putih, wortel, dan kentang; masak hingga sayuran empuk; tambahkan daun seledri, garam, dan merica; aduk rata, sajikan hangat.'],
            ['recipe_id' => 6, 'deskripsi_langkah' => 'Campurkan tepung terigu, gula pasir, baking powder, dan cokelat bubuk dalam sebuah wadah; tambahkan telur, susu cair, dan mentega cair; aduk rata hingga adonan tercampur sempurna; panaskan sedikit minyak di atas wajan; tuang adonan dan masak hingga kedua sisi pancake berwarna keemasan; sajikan dengan topping sesuai selera.'],
            ['recipe_id' => 7, 'deskripsi_langkah' => 'Siapkan kaldu bakso, rebus daging hingga empuk; bentuk bola-bola bakso, masukkan ke dalam kaldu, biarkan mendidih; sajikan bakso dengan mie dan pelengkap seperti sawi dan bakso goreng.'],
            ['recipe_id' => 8, 'deskripsi_langkah' => 'Campurkan bahan es krim, masukkan ke dalam mesin es krim, dan biarkan hingga mengental; sajikan dengan topping sesuai selera.'],
            ['recipe_id' => 9, 'deskripsi_langkah' => 'Siapkan adonan pizza, oleskan saus tomat, taburi dengan keju mozzarella dan daun basil; panggang hingga keju meleleh dan pinggirannya kecoklatan; sajikan hangat.'],
            ['recipe_id' => 10, 'deskripsi_langkah' => 'Siapkan bahan seperti mie instan atau mie telur, cabai merah, cabai rawit, bawang merah, bawang putih, kecap manis, saus tiram, kecap asin, sayuran (sawi, kol), dan ayam atau udang sesuai selera; Rebus mie hingga matang, tiriskan, dan sisihkan; Haluskan cabai merah, cabai rawit, bawang merah, dan bawang putih; Panaskan minyak, tumis bumbu halus hingga harum; Tambahkan ayam atau udang, masak hingga matang; Masukkan sayuran, aduk hingga layu; Masukkan mie, tambahkan kecap manis, saus tiram, dan kecap asin, aduk hingga bumbu merata; Angkat dan sajikan mie goreng pedas dengan taburan bawang goreng dan irisan cabai rawit sebagai pelengkap.'],
            ['recipe_id' => 11, 'deskripsi_langkah' => 'Siapkan bahan-bahan seperti tepung beras, santan, gula pasir, dan pewarna makanan; Campurkan tepung beras, santan, dan gula pasir, aduk hingga adonan rata dan tidak menggumpal; Bagi adonan menjadi beberapa bagian sesuai jumlah warna yang diinginkan, tambahkan pewarna makanan ke masing-masing bagian; Panaskan kukusan dan olesi loyang dengan minyak agar tidak lengket; Tuang lapisan pertama adonan ke dalam loyang dan kukus selama 5 menit; Tambahkan lapisan adonan berikutnya dengan warna berbeda, kukus kembali selama 5 menit; Ulangi langkah ini hingga semua adonan habis; Setelah lapisan terakhir, kukus seluruh kue selama 15 menit hingga matang; Angkat dan dinginkan sebelum dipotong dan disajikan.'],
            ['recipe_id' => 12, 'deskripsi_langkah' => 'Siapkan bahan seperti daging sapi, santan, cabai merah, bawang merah, bawang putih, jahe, lengkuas, daun jeruk, daun salam, serai, dan rempah-rempah lainnya; Haluskan bumbu seperti cabai merah, bawang merah, bawang putih, jahe, dan lengkuas; Panaskan minyak dalam wajan, tumis bumbu halus hingga harum; Masukkan potongan daging sapi dan aduk hingga berubah warna; Tuangkan santan ke dalam wajan, aduk perlahan agar santan tidak pecah; Tambahkan daun jeruk, daun salam, dan serai yang sudah dimemarkan; Masak dengan api kecil sambil terus diaduk hingga santan mengental dan minyak keluar; Biarkan rendang dimasak perlahan hingga bumbu meresap dan daging empuk; Angkat rendang dan sajikan hangat.'],
            ['recipe_id' => 13, 'deskripsi_langkah' => 'Siapkan bahan seperti sayuran segar (kangkung, kacang panjang, kol, tauge), tahu, tempe, kentang rebus, dan telur rebus; Rebus semua sayuran hingga matang, tiriskan; Goreng tahu dan tempe hingga kecokelatan, potong sesuai selera; Siapkan bumbu kacang dengan cara menghaluskan kacang tanah goreng, cabai, bawang putih, gula merah, dan garam, lalu tambahkan air asam jawa dan air hangat, aduk rata; Tata sayuran rebus, tahu, tempe, kentang, dan telur rebus di piring saji; Siram dengan bumbu kacang sesuai selera; Taburi bawang goreng dan kerupuk sebagai pelengkap; Sajikan gado-gado selagi segar.'],
            ['recipe_id' => 14, 'deskripsi_langkah' => 'Siapkan bahan seperti beras, santan, daun pandan, serai, daun salam, dan garam; Cuci beras hingga bersih, lalu tiriskan; Masak santan bersama daun pandan, serai, daun salam, dan garam hingga mendidih; Masukkan beras ke dalam santan mendidih, masak hingga santan terserap; Kukus beras hingga matang dan menjadi nasi uduk; Sajikan nasi uduk dengan pelengkap seperti ayam goreng, telur dadar, sambal, tempe goreng, dan kerupuk.'],
            ['recipe_id' => 15, 'deskripsi_langkah' => 'Siapkan bahan seperti sayuran segar (kol, tauge, kacang panjang, mentimun, terong hijau) dan bumbu kacang; Potong-potong sayuran segar sesuai selera; Haluskan bumbu kacang yang terdiri dari kacang tanah goreng, cabai, bawang putih, kencur, gula merah, garam, dan air asam jawa, tambahkan air hingga bumbu bertekstur kental; Campur sayuran dengan bumbu kacang, aduk hingga rata; Sajikan karedok dengan taburan kerupuk di atasnya.'],
            ['recipe_id' => 16, 'deskripsi_langkah' => 'Siapkan bahan seperti mie telur, ayam, bawang putih, bawang merah, kecap manis, kecap asin, saus tiram, daun bawang, dan kaldu ayam; Rebus mie telur hingga matang, tiriskan, dan sisihkan; Potong ayam menjadi dadu kecil; Tumis bawang putih dan bawang merah hingga harum, tambahkan potongan ayam dan masak hingga matang; Tambahkan kecap manis, kecap asin, saus tiram, dan sedikit kaldu ayam, masak hingga bumbu meresap; Siapkan mangkuk, letakkan mie, tambahkan ayam berbumbu di atasnya, dan siram sedikit kaldu panas; Tambahkan daun bawang, sawi rebus, dan bawang goreng sebagai pelengkap; Sajikan mie ayam hangat dengan sambal dan jeruk nipis.'],
            ['recipe_id' => 17, 'deskripsi_langkah' => 'Siapkan bahan seperti mie telur, ayam cincang, sawi hijau, bawang putih, bawang merah, kecap manis, kecap asin, saus tiram, minyak wijen, dan kaldu ayam; Rebus mie telur hingga matang, tiriskan, dan beri sedikit minyak agar tidak lengket; Tumis bawang putih dan bawang merah hingga harum, tambahkan ayam cincang, kecap manis, kecap asin, saus tiram, dan minyak wijen, masak hingga matang; Siapkan mangkuk, tata mie, tambahkan topping ayam berbumbu, dan siram sedikit kaldu panas; Tambahkan sawi hijau rebus, bawang goreng, dan pangsit goreng sebagai pelengkap; Sajikan hangat.'],
            ['recipe_id' => 18, 'deskripsi_langkah' => 'Siapkan bahan seperti alpukat, nangka, kelapa muda, cincau hitam, santan, gula merah cair, dan es serut; Potong alpukat, nangka, dan cincau hitam menjadi ukuran kecil-kecil; Siapkan mangkuk saji, tata potongan alpukat, nangka, cincau hitam, dan kelapa muda; Tambahkan santan dan gula merah cair sesuai selera; Beri es serut di atasnya, dan sajikan es teler segar.'],
            ['recipe_id' => 19, 'deskripsi_langkah' => 'Siapkan bahan seperti coklat bubuk, gula pasir, susu cair, agar-agar bubuk, dan air; Campurkan coklat bubuk, gula pasir, agar-agar bubuk, dan air dalam panci; Masak campuran di atas api sedang sambil diaduk hingga mendidih; Tuangkan campuran ke dalam cetakan puding; Diamkan hingga dingin dan mengeras; Simpan di kulkas hingga siap disajikan, sajikan dengan saus coklat jika diinginkan.'],
            ['recipe_id' => 10, 'deskripsi_langkah' => 'Siapkan bahan seperti daging ayam fillet, tusuk sate, kecap manis, bawang putih, ketumbar, garam, dan air jeruk nipis; Potong daging ayam menjadi kotak kecil, lalu marinasi dengan kecap manis, bawang putih halus, ketumbar, garam, dan air jeruk nipis selama 30 menit; Tusukkan daging ayam yang sudah dimarinasi ke tusuk sate; Bakar sate di atas bara api sambil diolesi sisa bumbu marinasi hingga matang; Sajikan sate ayam dengan lontong, bumbu kacang, dan irisan bawang merah.'],
            ['recipe_id' => 21, 'deskripsi_langkah' => 'Siapkan bahan seperti lontong, sayur labu siam, santan, daun salam, lengkuas, bawang merah, bawang putih, cabai, dan ebi; Tumis bawang merah, bawang putih, dan cabai hingga harum, tambahkan daun salam dan lengkuas; Masukkan labu siam yang sudah dipotong korek api, aduk hingga layu; Tuangkan santan, tambahkan garam dan gula sesuai selera, masak hingga mendidih; Tata lontong dalam piring, siram dengan sayur labu siam; Tambahkan pelengkap seperti kerupuk, sambal, dan telur rebus, lalu sajikan.']
        ]);
    }
}

